use_frameworks!

#xcodeproj 'NAMETests'
#workspace '../NAME'

target 'topsiOSPro' do
  pod 'topsiOSPro',:path => '../topsiOSPro'
#  pod 'topsiOSPro', :podspec => '../topsiOSPro.podspec'

  target 'topsiOSPro_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
