use_frameworks!

#xcodeproj 'NAMETests'
#workspace '../NAME'

target 'topsiOSPro_Example' do
  source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
  pod 'topsiOSPro',:path => '../'
#  pod 'topsiOSPro', :podspec => '../topsiOSPro.podspec'

  target 'topsiOSPro_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
